FactoryGirl.define do
  factory :terminal_android do
    media_user nil
    identifier "MyString"
    info '{"HARDWARE":"qcom","VERSION.SDK_INT":"19","RADIO":"unknown","VERSION_CODES.BASE":"1","VERSION_CODES.GINGERBREAD_MR1":"10","VERSION.INCREMENTAL":"yb5_jg","VERSION.SDK":"19","HOST":"BuildHost","VERSION_CODES.HONEYCOMB":"11","VERSION_CODES.HONEYCOMB_MR1":"12","TAGS":"release-keys","VERSION.RESOURCES_SDK_INT":"19","VERSION_CODES.HONEYCOMB_MR2":"13","VERSION_CODES.JELLY_BEAN_MR1":"17","VERSION_CODES.CUPCAKE":"3","VERSION_CODES.JELLY_BEAN_MR2":"18","ID":"14.3.B.0.310","VERSION_CODES.BASE_1_1":"2","VERSION_CODES.ICE_CREAM_SANDWICH":"14","MANUFACTURER":"Sony","TYPE":"user","VERSION_CODES.ECLAIR_0_1":"6","VERSION_CODES.GINGERBREAD":"9","TIME":"1406102597000","FINGERPRINT":"docomo/SO-01F/SO-01F:4.4.2/14.3.B.0.310/yb5_jg:user/release-keys","VERSION_CODES.KITKAT":"19","UNKNOWN":"unknown","BOARD":"MSM8974","VERSION_CODES.ECLAIR_MR1":"7","VERSION_CODES.FROYO":"8","VERSION_CODES.ICE_CREAM_SANDWICH_MR1":"15","PRODUCT":"SO-01F","DISPLAY":"14.3.B.0.310","USER":"BuildUser","VERSION_CODES.JELLY_BEAN":"16","VERSION_CODES.ECLAIR":"5","DEVICE":"SO-01F","BOOTLOADER":"s1","MODEL":"SO-01F","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","VERSION_CODES.CUR_DEVELOPMENT":"10000","IS_DEBUGGABLE":"false","VERSION.CODENAME":"REL","VERSION.RELEASE":"4.4.2","VERSION_CODES.DONUT":"4","SERIAL":"CB5125LZM8","BRAND":"docomo"}{"HARDWARE":"qcom","VERSION.SDK_INT":"19","RADIO":"unknown","VERSION_CODES.BASE":"1","VERSION_CODES.GINGERBREAD_MR1":"10","VERSION.INCREMENTAL":"yb5_jg","VERSION.SDK":"19","HOST":"BuildHost","VERSION_CODES.HONEYCOMB":"11","VERSION_CODES.HONEYCOMB_MR1":"12","TAGS":"release-keys","VERSION.RESOURCES_SDK_INT":"19"'
    android_version "1.0.0"
    android_registration_id "MyString"
    available true
  end

end
